In [1]:
import torch
import numpy as np

In [2]:
array = [1,2,3,4,5]
array

[1, 2, 3, 4, 5]

In [6]:
type(array)

list

In [7]:
multi_array = [[1,2,3,4] , [5,6,7,8]]
multi_array

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
type(multi_array)

list

In [9]:
import numpy as np

In [10]:
np1 = np.random.rand(3,4)
np1

array([[0.38747555, 0.18907434, 0.82986704, 0.99178607],
       [0.26727483, 0.94061495, 0.56463613, 0.11320672],
       [0.3035187 , 0.4343422 , 0.22946688, 0.43990072]])

In [11]:
np1.dtype

dtype('float64')

In [12]:
import torch

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.1428,  0.9886, -0.5278,  0.1667],
        [ 0.4940, -0.6601, -0.7457,  2.2471],
        [ 0.3609,  0.2319, -0.6471, -0.3218]])

In [18]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
tensor_3d.dtype

torch.float32

In [26]:
np_tensor = torch.tensor(np1)
np_tensor

tensor([[0.3875, 0.1891, 0.8299, 0.9918],
        [0.2673, 0.9406, 0.5646, 0.1132],
        [0.3035, 0.4343, 0.2295, 0.4399]], dtype=torch.float64)

In [29]:
np_tensor.dtype

torch.float64

In [31]:
np_tensor = np_tensor.to(torch.float32)
np_tensor

tensor([[0.3875, 0.1891, 0.8299, 0.9918],
        [0.2673, 0.9406, 0.5646, 0.1132],
        [0.3035, 0.4343, 0.2295, 0.4399]])

In [34]:
np_tensor.dtype

torch.float32